- name: Update DB Servers
  hosts: dbservers

  tasks:
  - name: Install SQLite3
    ansible.builtin.apt:
      name: sqlite3
      state: latest

  - name: Install Go
    ansible.builtin.apt:
      name: golang-go
      state: latest

  - name: Get ScratchDB Repo
    ansible.builtin.git:
      repo: 'https://github.com/chathamabate/SDSubmission.git'
      dest: ~/sd

  - name: Build Server Binary
    ansible.builtin.shell:
      cmd: go build -o ~/sd-server
      chdir: ~/sd/backend/cmd

  - name: Stop Old Server (If Running)
    command: 'pkill -2 -f sd-server'
    ignore_errors: true

  - name: Start New Server
    command: '~/sd-server'
    async: 1000 # This number is just a placeholder.
                # The playbook should exit without terminating
                # the new server.
    poll: 0

